name: Docker Publish
on:
  push:
    branches:
      - main
permissions: 
  contents: read
  packages: write
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: Git Checkout
         uses: actions/checkout@v7.0.0
       - name: Docker Login
         uses: docker/login-action@v4.2.0
         with:
           username: ${{ github.actor }}
           password: ${{ github.GITHUB_TOKEN }}
           registry: ghcr.io
       - name: Build
         run: |
          docker build . --tag=ghcr.io/manodevs/skills-publish-docker-images/stackoverflown:latest
          docker push ghcr.io/manodevs/skills-publish-docker-images/stackoverflown:latest
        
     
